from __future__ import annotations

import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from promote_project_note import note_problems, select_note


VALID_NOTE = """---
type: project
status: active
---

# Vibe Coding Dojo

## Summary

Shared context for the Maze project.

## Current Files

- `dojo_app/maze_game.py`
- `dojo_app/maze_play.py`

## Boundaries

- Keep movement scoped to the play module.

## Verification

- python3 scripts/check_repo.py
"""


LIVE_NANO_OUTPUT = """Current Maze files
- Maze.txt generated by MazeMaker and consumed by the maze game.

Agent boundaries
- Scope: only modify the next_position function in maze_play.

Verification commands
- python3 -m maze_game --maze-file maze.txt --check-only
"""


STAGING_NANO_OUTPUT = """---
title: Vibe Coding Dojo
project: maze-play
---

# Vibe Coding Dojo

## Summary

Shared context for the Maze project.

## Current Files

- `dojo_app/maze_game.py`
- `dojo_app/maze_play.py`

## Boundaries

- Keep movement scoped to the play module.

## Verification

- python3 scripts/verify_maze_movement.py
"""


class PromoteProjectNoteTests(unittest.TestCase):
    def test_valid_codex_draft_is_selected(self):
        selected, source = select_note(VALID_NOTE, "unused")

        self.assertEqual(source, "codex-draft")
        self.assertEqual(selected, VALID_NOTE)

    def test_staging_frontmatter_is_normalized(self):
        selected, source = select_note(STAGING_NANO_OUTPUT, VALID_NOTE)

        self.assertEqual(source, "codex-draft")
        self.assertTrue(selected.startswith("---\ntype: project\nstatus: active\n---"))
        self.assertNotIn("project: maze-play", selected)

    def test_live_nano_output_restores_checked_note(self):
        selected, source = select_note(LIVE_NANO_OUTPUT, VALID_NOTE)

        self.assertEqual(source, "checked-repo-note")
        self.assertEqual(selected, VALID_NOTE)
        self.assertIn("# Vibe Coding Dojo", note_problems(LIVE_NANO_OUTPUT))

    def test_invalid_fallback_is_rejected(self):
        with self.assertRaisesRegex(ValueError, "checked project note is invalid"):
            select_note(LIVE_NANO_OUTPUT, "# incomplete")


if __name__ == "__main__":
    unittest.main()
